set $wal_background     {background}
set $wal_background_alt {color0}
set $wal_foreground     {foreground}
set $wal_foreground_alt {color7}
set $wal_muted          {color8}
set $wal_accent         {color4}
set $wal_accent_alt     {color6}
set $wal_alert          #BF616A
