[colors]
draw_bold_text_with_bright_colors = true

[colors.primary]
background = "0x0B1118"
foreground = "0xD8DEE9"

[colors.normal]
black = "0x101A24"
red = "0xBF616A"
green = "0xA3BE8C"
yellow = "0xEBCB8B"
blue = "0x81A1C1"
magenta = "0xB48EAD"
cyan = "0x88C0D0"
white = "0xE5E9F0"

[colors.bright]
black = "0x4C566A"
red = "0xBF616A"
green = "0xA3BE8C"
yellow = "0xEBCB8B"
blue = "0x81A1C1"
magenta = "0xB48EAD"
cyan = "0x00D1FF"
white = "0xECEFF4"
